#!/usr/bin/python

import argparse
import os

from zenias_functions import (z_check_dir,
                              z_logo,
                              z_make_templates,
                              z_success)
from zenias_version import Z_VERSION

# Logo
z_logo()
#
# Parser for arguments
#
parser = argparse.ArgumentParser(prog='zenias_template')
# Language argument
parser.add_argument('language', type=str,
                    help='The language/module name')
# Directory argument
parser.add_argument('-d', '--directory', type=str, default='.',
                    help='Directory where to create the template. Default is the current dir.')
args = parser.parse_args()


target = os.path.abspath(args.directory)
script = os.path.dirname(os.path.realpath(__file__))

# Create the new dir
z_check_dir(target)

z_make_templates(os.path.join(script, 'skeleton'), target, dict(Z_VERSION=Z_VERSION, Z_LANG=args.language))

z_success('Your new template is ready for customization in ' + target)
