#!/bin/bash -   
#title          :zenias
#description    :Zenias bash script for linux
#author         :Manuel Tancoigne
#date           :20160612
#version        :0.1    
#usage          :./zenias <command> <arguments>
#notes          :       
#bash_version   :4.3.42(1)-release
#============================================================================
# Activate python env
# Is there another way of doing that ?
source .python_env/bin/activate
# Launch Zenias
python zenias.py "$@"
# Deactivate it
deactivate
