#!/usr/bin/env bash

# Making the arguments of the zeus command available to the whole script
export zeusargv1=$1
export zeusargv2=$2
export zeusargv3=$3

gitconfig () {
    # Ask user for input to set up GitHub and git configs.
    read -p "What is your real name? >>> " username
    read -p "What is your Github email address? >>> " email
    read -p "what is your Github username? >>> " githubusername
    git config --global user.email "$email"
    git config --global user.name "$username"
    # Set push to simple
    git config --global push.default simple
    # Store the GitHub username inside github_config so that gitcreate
    # can retrieve the username to perform Github API call
    echo "githubusername: $githubusername" >> /home/vagrant/.configs/github_config
}

gitcreate () {
    # Create a private or public repo on Github
    read -p "How should the Github remote repo be called? >>> " remoterepo
    # Get the stored GitHub username inside github_config
    githubname=$(cat ~/.configs/github_config | egrep "githubusername" | tail -1 | awk '{print $2}')
    # Loop to create the remote repo
    case $zeusargv2 in
        private)
            curl -u "$githubname" https://api.github.com/user/repos -d '{"name":'"\"$remoterepo\""',"private":"true"}' > ~/.configs/.githubremote
            newgithubremote=$(cat ~/.configs/.githubremote | egrep "html_url" | tail -1 | awk '{print $2}' | sed -r 's/[",]//g')
            git remote add origin $newgithubremote
            git push --set-upstream origin master
            ;;
        public)
            curl -u "$githubname" https://api.github.com/user/repos -d '{"name":'"\"$remoterepo\""'}' > ~/.configs/.githubremote
            newgithubremote=$(cat ~/.configs/.githubremote | egrep "html_url" | tail -1 | awk '{print $2}' | sed -r 's/[",]//g')
            git remote add origin $newgithubremote
            git push --set-upstream origin master
            ;;
    esac
}

create () {
    # Create a new project directory named after the third argument.
    # Options available for -python
    case $zeusargv2 in
        -python)
        # Installs all dependencies needed for the Python stack
            mkdir $zeusargv3
            BASEDIR=$(dirname "$0")
            cp $BASEDIR/python/.gitignore $PWD/$zeusargv3
            cp $BASEDIR/python/Procfile $PWD/$zeusargv3
            cp $BASEDIR/python/runtime.txt $PWD/$zeusargv3
            cp $BASEDIR/python/Vagrantfile $PWD/$zeusargv3
            cp $BASEDIR/python/provision.sh $PWD/$zeusargv3
            cp $BASEDIR/python/requirements.txt $PWD/$zeusargv3
            cp $BASEDIR/python/.bashrc $PWD/$zeusargv3
            cp $BASEDIR/zeus $PWD/$zeusargv3
            cd $PWD/$zeusargv3
            git init
            vagrant up
            vagrant ssh
            ;;

        -pythontest)
        # Installs all dependencies needed for testing the Python stack
            mkdir $zeusargv3
            BASEDIR=$(dirname "$0")
            cp $BASEDIR/python/.gitignore $PWD/$zeusargv3
            cp $BASEDIR/python/Procfile $PWD/$zeusargv3
            cp $BASEDIR/python/runtime.txt $PWD/$zeusargv3
            cp $BASEDIR/python/Vagrantfile $PWD/$zeusargv3
            cp $BASEDIR/python/provision.sh $PWD/$zeusargv3
            cp $BASEDIR/python/requirements.txt $PWD/$zeusargv3
            cp $BASEDIR/python/.bashrc $PWD/$zeusargv3
            cp $BASEDIR/zeus $PWD/$zeusargv3
            cp -r $BASEDIR/python/python_test $PWD/$zeusargv3
            cd $PWD/$zeusargv3
            git init
            vagrant up
            vagrant ssh
            ;;

        -bootstrap)
        # Install all dependencies needed for Bootstrap stack
            mkdir $zeusargv3
            BASEDIR=$(dirname "$0")
            cp $BASEDIR/bootstrap/.gitignore $PWD/$zeusargv3
            cp $BASEDIR/bootstrap/composer.json $PWD/$zeusargv3
            cp $BASEDIR/bootstrap/home.html $PWD/$zeusargv3
            cp $BASEDIR/bootstrap/index.php $PWD/$zeusargv3
            cp $BASEDIR/bootstrap/.bashrc $PWD/$zeusargv3
            cp $BASEDIR/bootstrap/Vagrantfile $PWD/$zeusargv3
            cp $BASEDIR/bootstrap/provision.sh $PWD/$zeusargv3
            cp $BASEDIR/zeus $PWD/$zeusargv3
            cd $PWD/$zeusargv3
            git init
            vagrant up
            vagrant ssh
            ;;
    esac
}

# Choice of which function to use based on user input of zeus' arguments
case $zeusargv1 in
    gitconfig)
        gitconfig
        ;;
    gitcreate)
        gitcreate
        ;;
    create)
        create
        ;;
    help)
        echo "Zeus - the tool to make web development faster"
        echo "You have the following commands: zeus gitconfig, zeus gitcreate private, zeus gitcreate public."
        echo "You need to run zeus gitconfig first in order to use the rest"
        echo "zeus gitconfig creates or overwrites existing git username, email, and push configurations."
        echo "zeus gitcreate creates a public or private GitHub repo depending on the second argument you give."
        ;;
    *)
        echo "Invalid argument parsed"
        ;;
esac
