#!/usr/bin/env bash
# Generated by zenias_template v$Z_VERSION

#-------------------------------------------------------------------------------
# Vagrant configuration file for a zenias box
#-------------------------------------------------------------------------------

# Define some vars here.
# ----------------------
# PROJECT="my_project"
# DB="my_app"
# ...

# NOTE:
# -----
# This file is executed by root user - sudo not needed
# If you need to create files and dirs rw accessible by the user,
# either change their permissions after creation, or use
# su - vagrant -c "<creation-command>"

# Limits the interactive mode
export DEBIAN_FRONTEND=noninteractive
# Header
echo "---------------------------------------------"
echo "Running vagrant provisioning"
echo "---------------------------------------------"

# Install heroku toolbelt
echo "- Adding heroku toolbelt to packages sources "
# These shell script snippets are directly taken from heroku installation script
echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
# install heroku's release key for package verification
wget -O- https://toolbelt.heroku.com/apt/release.key 2>&1 | apt-key add -

echo "---------------------------------------------"
echo "------- Updating package dependencies -------"
echo "---------------------------------------------"
apt-get update -y # no need for sudo, and -y is needed to bypass the yes-no

echo "---------------------------------------------"
echo "-------- Installing packages ----------------"
echo "---------------------------------------------"

# Basic packages installation
# This is the default stack for an empty box.
# You can add yours here, or add your own list below
# for a better script maintenance.
apt-get install -y --no-install-recommends heroku-toolbelt ruby dos2unix man curl

# Additionnal packages :
# A good thing is to explain why you use package x or y:
# x - Added because needed for <something>
# y - Added as mandatory for <something_else>
#apt-get install -y --no-install-recommends x y

# Install Heroku CLI
# ------------------
su - vagrant -c "heroku --version > /dev/null 2>&1"


# Ex: DB confing
# Installing a postgresql db. This is left as an example
# por this to wor, you should have installed the appropriate packages
#echo "---------------------------------------------"
#echo "---- Setting up postgresql with $${DB} DB ----"
#echo "---------------------------------------------"
# Creating superuser (-s) vagrant
#su - postgres -c "createuser -s vagrant"
#su - vagrant -c "createdb $${DB}"

# Setting default password for vagrant so it's accessible from the host
#su - vagrant -c "psql -U vagrant -d $${DB} -c \"ALTER USER \\\"vagrant\\\" WITH PASSWORD 'vagrant';\""

# Copying files
# -------------
# Be sure the files exists :)
#
# By default, you should at least have the bashrc copy, as it declares the PATH variable
# adding zenias_bin to it
echo "---------------------------------------------"
echo "------- Copying files -----------------------"
echo "---------------------------------------------"
cat /vagrant/vagrant/bashrc >> /home/vagrant/.bashrc

# All done
echo "---------------------------------------------"
echo "Everything is up. Use 'vagrant ssh' to log on"
echo "your new box."
echo "---------------------------------------------"

exit 0
