---
driver:
  name: vagrant
  provider: virtualbox
provisioner:
  name: chef_zero

platforms:
  - name: windows2012r2_chef12
    driver:
      box_url: <%= ENV['WINDOWS_BOX_URL'] %>
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[test_archive]
